### ISSUE TITLE
Add Hugo - Best practices

### ISSUE THREAD

**Issue by spech66** [theNewDynamic/awesome-hugo#38]
Hi @budparr thank you for maintaining this awesome list.

I'm the maintainer of the [Hugo - Best practices](https://github.com/spech66/hugo-best-practices) collection. This is a combination of front-end best practices and helpful snippets to get Hugo running fast and with good scores. Maybe this might be usefule for the awesome list.

Best regards
Sebastian

**Comment by budparr** [comment]
Thanks!
