### ISSUE TITLE
Publish awesome-hugo.dev to a "real" website instead of a GitHub redirect

### ISSUE THREAD

**Issue by davidsneighbour** [theNewDynamic/awesome-hugo#41]
Rework the list into a real Hugo website and let people end up on a nice (interactive) site. You could host on Netlify. Add a search. Add a form to add items. Don't make it GitHub-centric. 

I saw you have a domain awesome-hugo.dev - let's use it ;)

**Comment by budparr** [comment]
I like the idea, but I haven't had time lately.

**Comment by davidsneighbour** [comment]
I'll invest, please keep this open ;)
