### ISSUE TITLE
Adding Hugo book - Hugo in Action

### ISSUE THREAD

**Issue by atishay** [theNewDynamic/awesome-hugo#47]
https://www.manning.com/books/hugo-in-action - Should this be a new section. Its more than an article.

**Comment by contributorpw** [comment]
<table>
<tr>
    <th>Title
    <th>Author
    <th>Code
    <th>Published
    <th>Pages
<tr>
	<td>Build Websites with Hugo. Fast Web Development with Markdown
	<td>Brian P. Hogan
	<td>ISBN: 9781680507263
	<td>2020
	<td>154
</table>

**Comment by atishay** [comment]
That's a different one. The one I am writing is this one:

| Title |	Author |	Code |	Published |	Pages |
| --- | --- | --- | --: | --: |
| Hugo in Action - Static sites and dynamic Jamstack apps |	Atishay Jain | 	ISBN: 9781617297007 |	2021 |	350

**Comment by budparr** [comment]
Definitely a new section, just above articles. Thanks!
